### ISSUE TITLE
error running example on linux

### ISSUE THREAD

**Issue by edvail** [rannn505/node-powershell#12]
When I try to run provided example on ubuntu with powershell 6 installed on it i getting folowing error:
```
<node-powershell>:: Process undefined started

<node-powershell>:: Command invoke started



Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at /home/ed/git/alsocloud.visualstudio.com/ac-worker/node_modules/node-powershell/dist/Shell.js:133:36
    at Shell.invoke (/home/ed/git/alsocloud.visualstudio.com/ac-worker/node_modules/node-powershell/dist/Shell.js:130:20)
    at /home/ed/git/alsocloud.visualstudio.com/ac-worker/src/index.js:7:19
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by IonicaBizau** [comment]
I addressed this in the [`powershell`](https://github.com/IonicaBizau/powershell) package. /cc https://github.com/IonicaBizau/powershell/pull/4 :boom:

**Comment by rannn505** [comment]
Hey @edvail, @IonicaBizau 
Please check out the new features entered in the last commit.
I just waited for Microsoft to get to 6.0.0.10-alpha version. 
Thank you for your patience.  :+1:
